name: 'Issue Link'
on:
  pull_request:
    types: [opened]

jobs:
  issue-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add issue links
        uses: ./
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: 'issue-'
          resolve: 'true'
